include_guard()

function(enable_sanitizers SANITIZER_ADDRESS SANITIZER_UNDEFINED SANITIZER_LEAK SANITIZER_THREAD)
    set(SANITIZERS_LIST "")
    if(SANITIZER_ADDRESS)
        message(STATUS "AddressSanitizer enabled")
        if (SANITIZER_THREAD)
            message(FATAL "Cannot use ADDRESS SANITIZER alongside THREAD SANITIZER")
        endif()
        list(APPEND SANITIZERS_LIST "address")
    endif()
    if(SANITIZER_UNDEFINED)
        message(STATUS "UndefinedBehaviorSanitizer enabled")
        list(APPEND SANITIZERS_LIST "undefined")
    endif()
    if(SANITIZER_LEAK)
        message(STATUS "LeakSanitizer enabled")
        list(APPEND SANITIZERS_LIST "leak")
    endif()
    if(SANITIZER_THREAD)
        message(STATUS "ThreadSanitizer enabled")
        if (SANITIZER_ADDRESS)
            message(FATAL "Cannot use ADDRESS SANITIZER alongside THREAD SANITIZER")
        endif()
        list(APPEND SANITIZERS_LIST "thread")
    endif()
    
    set(SANITIZER_COMPILER_FLAGS "" PARENT_SCOPE)
    set(SANITIZER_LINKER_FLAGS "" PARENT_SCOPE) 
    
    if (SANITIZERS_LIST)
        string(JOIN "," SANITIZERS_JOINED "${SANITIZERS_LIST}")
        set(SANITIZER_COMPILER_FLAGS "-fsanitize=${SANITIZERS_JOINED}" PARENT_SCOPE)
        set(SANITIZER_LINKER_FLAGS "-fsanitize=${SANITIZERS_JOINED} -fno-omit-frame-pointer" PARENT_SCOPE)
    endif()
endfunction()
